### ISSUE TITLE
Set a 'focus_date' for each Timeline

### ISSUE THREAD

**Issue by clioweb** [scholarslab/NeatlineTime#1]
As of @4f7a884697a0a1a67e60678c57a1f40d76855f2c NeatlineTime starts at the earliest item on the timeline. However, we should decide on defaults and options. A few come to mind:

1. Date the timeline was created/modified
2. Date chosen by the user
3. Midpoint for all the events/items on the Timeline.

Seems like letting the user choose the focus date, with a few possible suggestions (like earliest date or midpoint) would be ideal. If the user doesn't set a date, it should default to the earliest date.

**Comment by csbailey5t** [comment]
Closed in f81ed8fb2939fd6a6bd880d499f3312f0c75801c
