### ISSUE TITLE
NeatlineTime overwrites with old jQuery, breaking other plugins.

### ISSUE THREAD

**Issue by adamfranco** [scholarslab/NeatlineTime#61]
The local jquery verion in [simile-ajax-bundle.js](https://github.com/scholarslab/NeatlineTime/blob/master/views/shared/javascripts/simile/ajax-api/simile-ajax-bundle.js) is out of date and replacing the jQuery shipped with Omeka. This causes Neatline Time to conflict with the BulkMetadataEditor plugin by replacing the version of jQuery on the page (1.11.2) with the older version at `SimileAjax.jQuery` (1.2.6). While this doesn't break the public view, the admin view of the NeatlineTime timelines has a javascript error if BulkMetadataEditor is also installed due to BulkMetadataEditor expecting a newer version of jQuery.

[NeatlineTimeFunctions.php, line 75](https://github.com/scholarslab/NeatlineTime/blob/master/helpers/NeatlineTimeFunctions.php#L75):

    function queue_timeline_assets()
    {
      ...
      $headScript->appendScript('SimileAjax.History.enabled = false; window.jQuery = SimileAjax.jQuery');
      ...
    }

Removing the call to `window.jQuery = SimileAjax.jQuery` seems to fix things, but maybe the duplicate old jQuery just isn't needed any more and can be removed.

**Comment by csbailey5t** [comment]
Hi @adamfranco I haven't been able to reproduce this. If it's still relevant, can you specify which versions of Omeka and the various plugins you're using?

**Comment by csbailey5t** [comment]
Closed unless it pops up again.
