### ISSUE TITLE
Neatline Timeline plugin use File instead of Item

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineTime#62]
From @tamielbr on scholarslab/Neatline#367:

> I'm trying to plot a timeline where each element is a FILE and not an ITEM. Since they both use DC and have a "date" element, I thought it would pick up, but it doesn't seem to, even if I use the specific item number (#xxx). I'm trying to plot a single item as it changes over time with its pictures, and all of the images are a single Item.

**Comment by clioweb** [comment]
If this is of interest, might be worth expanding this out to any possible Omeka Record. Collections also have Dublin Core, for example.

**Comment by clioweb** [comment]
Actually, this may be a duplicated of, or at least related to, #50.

**Comment by erochest** [comment]
This *is* a duplicate of #50. Closing.
