### ISSUE TITLE
bug: placing two Neatline Time timelines on one Omeka exhibit page makes both timelines blank

### ISSUE THREAD

**Issue by sylviachong** [scholarslab/NeatlineTime#64]
I've been trying to break up my Neatline Time segments into half-century chucks so they are easier to see and scroll through. However, when I place two timelines on the same page, both of them break -- they show no items, and start on random dates. (I know the timelines have valid item queries because they look fine when examined individually in the Neatline Time listings.) 

See example of bug at: http://vietnamwar.neatline-uva.org/exhibits/show/cambodia-timeline-test/cambodia-timeline

**Comment by erochest** [comment]
Nice. Thanks for the report.

I'm planning to devote some time for this plugin over the next few weeks (around start-of-semester chaos). I hope to address the issues you're raising during that. Thanks for taking the time to fill them all out.

**Comment by csbailey5t** [comment]
I have replicated this locally. The data is being loaded, but the center is being set incorrectly. The first timeline on the page defaults to the current date, while the center of the second timeline is set to the earliest date of the first timeline. Not sure yet why this is the case, but it appears to be so both locally and in the Vietnam War timeline page above.

**Comment by csbailey5t** [comment]
@sylviachong We figured out the problem at the root of the issue, and have fixed it in the code on Github. We also have fixed it directly on your Vietnam War exhibit. For the moment, this fix isn't in the official release of the plugin, but we will be cutting a new release containing it in the near future.
