### ISSUE TITLE
MySQL version hell

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineTime#75]
Looking at https://github.com/scholarslab/NeatlineTime/blob/master/NeatlineTimePlugin.php#L59-L60

What this does is have one field that set to the current time when the row is inserted, and one field that set to the current time whenever the row is updated.

So here are the issues:
- Before MySQL 5.6, you couldn't have two fields with `DEFAULT CURRENT_TIMESTAMP`, so this is how you handled it;
- However, if [`NO_ZERO_DATE`](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date) is set, this idiom throws an error;
- With 5.6, the first restriction is taken away, so there's no problem.

The issues comes in when you're dealing with MySQL 5.6 with `NO_ZERO_DATE` set.

The kludge I used is to insert this line before executing the query:

``` php
$this->_db->query("SET SQL_MODE='ALLOW_INVALID_DATES';");
```

Short of changing server config, which isn't always an option, I don't see a way around this. So this is just here for documentation.

**Comment by zerocrates** [comment]
The Omeka core's workaround for this is to have an arbitrary date as the default (avoiding the implied `CURRENT_TIMESTAMP` default), and set the actual default explicitly from the PHP side with the Timestamp mixin. (see omeka/Omeka#678).

**Comment by erochest** [comment]
Thanks. I suspect that will be what we'll end up doing.
