### ISSUE TITLE
Strict standards violations in NeatlineTimeTimelineTable

### ISSUE THREAD

**Issue by zerocrates** [scholarslab/NeatlineTime#76]
NeatlineTimeTimelineTable causes the following strict standards warnings:

> Strict Standards: Declaration of NeatlineTimeTimelineTable::filterByPublic() should be compatible with Omeka_Db_Table::filterByPublic(Omeka_Db_Select $select, $isPublic) in /mnt/storage/htdocs/omeka/plugins/NeatlineTime/models/NeatlineTimeTimelineTable.php on line 0
> 
> Strict Standards: Declaration of NeatlineTimeTimelineTable::filterByFeatured() should be compatible with Omeka_Db_Table::filterByFeatured(Omeka_Db_Select $select, $isFeatured) in /mnt/storage/htdocs/omeka/plugins/NeatlineTime/models/NeatlineTimeTimelineTable.php on line 0
> 
> Strict Standards: Declaration of NeatlineTimeTimelineTable::filterByUser() should be compatible with Omeka_Db_Table::filterByUser(Omeka_Db_Select $select, $userId, $userField) in /mnt/storage/htdocs/omeka/plugins/NeatlineTime/models/NeatlineTimeTimelineTable.php on line 0

The current (released) Omeka autoloader config hides these so you don't normally see them. A future release will fix that problem (and current master does already) and then they'll become visible when error reporting is turned on.

**Comment by erochest** [comment]
Thanks for bringing this to our attention. We're working on a release right now, and I think I've had to fix these to get tests to pass.
