### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by ColeDCrawford** [scholarslab/NeatlineTime#86]
When installing Neatline Time, I get a fatal error and cannot finish installing the plugin. I have Neatline and the other Neatline plugins installed and working successfully.

**User**
**Browser**	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
**Role**	super
**System**
Omeka	2.5
PHP	5.6.30 (cgi-fcgi)
OS	Linux 3.10.0-427.18.2.lve1.4.27.el7.x86_64 x86_64
MySQL Server	5.6.35
MySQL Client	mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
**PHP Extensions**
Regular	bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dba, dom, enchant, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, ionCube Loader, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, Reflection, session, shmop, SimpleXML, snmp, soap, sockets, SourceGuardian, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib
Zend	the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured)
**Plugins**
AddItemLink	0.1
AdminImages	1.3
CSSEditor	1.0.1
Coins	2.0.3
DocsViewer	2.1
ElementTypes	0.4
Escher	1.0.1
ExhibitBuilder	3.3.3
FacetByMetadata	1.0.2 (inactive)
Geolocation	2.2.5
ItemOrder	2.0.2
ItemRelations	2.0.2
Neatline	2.5.1
NeatlineFeatures	2.0.5
NeatlineSimile	2.0.4
NeatlineText	1.1.0
NeatlineWaypoints	2.0.2
RecordRelations	2.0.1
ShortcodeCarousel	1.0.1
SimplePages	3.0.8
SimpleVocab	2.1
TextAnnotation	0.2 (inactive)
UserProfiles	1.1.1
**Themes**
avantgarde	1
berlin	2.4
bigstuff	1.0
default	2.4 (current)
minimalist	2.3
seasons	2.4

Here's the error trace:
`2017-03-01T19:59:37+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Invalid default value for 'center_date'' in /home/exhibiti/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/exhibiti/public_html/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/exhibiti/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...')
#3 /home/exhibiti/public_html/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#4 /home/exhibiti/public_html/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->__call('query', Array)
#5 /home/exhibiti/public_html/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->query('CREATE TABLE IF...')
#6 [internal function]: NeatlineTimePlugin->hookInstall(Array)
#7 /home/exhibiti/public_html/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#8 /home/exhibiti/public_html/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#9 /home/exhibiti/public_html/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#10 /home/exhibiti/public_html/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#11 /home/exhibiti/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#12 /home/exhibiti/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /home/exhibiti/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /home/exhibiti/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /home/exhibiti/public_html/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#16 /home/exhibiti/public_html/admin/index.php(28): Omeka_Application->run()
#17 {main}`

**Comment by Daniel-KM** [comment]
Hi,

There is an issue in the database, see #75 and #76. They are fixed in my last pull request, but not committed here. So try my fork: https://github.com/Daniel-KM/NeatlineTime.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by ColeDCrawford** [comment]
Thanks Daniel - your patch looks good and works for me. +1 for committing this.

**Comment by scoutcalvert** [comment]
Another thanks for Daniel. Fixed my problem.

**Comment by bksw** [comment]
Hi!  So I have the same problem and I'm way over my head when it comes to doing the fix.  Is the patch a file I have to install in a specific folder on my hosting space?  I realize this is a really basic question, but I'm really excited about setting up my page and think that neatline would be perfect if I can get it up and running (I'm an archaeologist working at a site with a long occupation history, so the timeline plugin is really important!).

Thanks!

**Comment by Daniel-KM** [comment]
You have to remove the whole original plugin and to replace it with the fork. Simply download it, unzip it, rename it to NeatlineTime and this is ok.

**Comment by bksw** [comment]
Thank you, Daniel!!!  That worked.

**Comment by KarlYee** [comment]
Daniel - Thank you!  It fixed the problem.

**Comment by ebonweaver** [comment]
Disappointing that this plugin was published on the Omeka website and it's never actually worked, and still doesn't a year later.

**Comment by teo1978** [comment]
I have just downloaded the plugin right now from https://omeka.org/classic/plugins/ and I'm observing the exact samne issue.

This is not fixed. Please reopen.
