### ISSUE TITLE
Timeline completely empty

### ISSUE THREAD

**Issue by irmng** [scholarslab/NeatlineTime#92]
Hello,

Neatline Time installed properly but fails entirely to display any content! Our system adminstrator has ensured write permissions are all set and has checked the logs for errors but none are reported. But the timelines remains entirely empty:-

![image](https://user-images.githubusercontent.com/45592862/54617516-49ab0400-4a59-11e9-9bfa-f901b58911cf.png)

Please could you suggest what could be going wrong?

Thanks,
Richard

**Comment by Daniel-KM** [comment]
In the config form of the module, did you set simile internal ?
And you should set an item query that returns the items. And the items are returned only if they have a metadata for the date (element that you can select in "edit metadata"). And the date should be iso-8601 written.
So are all of these points ready?

**Comment by irmng** [comment]
Thanks for getting back to me.

Our systems admin people are not quite clear where we set 'simile internal' -  could you let me know if this is configured in the web interface or command line/config files?

All dates are in ISO-8601 so that seems to be fine.

Thanks!
Richard

________________________________

**Comment by Daniel-KM** [comment]
In the main config form of the plugin, the two first options. They are set by default, because it works in all cases.

**Comment by jeremyboggs** [comment]
@irmng Can you confirm Daniel's suggestion helped? If so, I can close this issue. If not, and if you're still interested, we can discuss other ways to debug your issue.
