### ISSUE TITLE
MySQL exception requiring only one TIMESTAMP column use CURRENT_TIMESTAMP as default.

### ISSUE THREAD

**Issue by teo1978** [scholarslab/NeatlineTime#93]
When installing the plugin I get this exception:

```
exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause' in /srv/www/antoniabad.info/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...')
#3 /srv/www/antoniabad.info/public_html/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#4 /srv/www/antoniabad.info/public_html/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->__call('query', Array)
#5 /srv/www/antoniabad.info/public_html/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->query('CREATE TABLE IF...')
#6 [internal function]: NeatlineTimePlugin->hookInstall(Array)
#7 /srv/www/antoniabad.info/public_html/application/libraries/Omeka/Plugin/Broker.php(142): call_user_func(Array, Array)
#8 /srv/www/antoniabad.info/public_html/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#9 /srv/www/antoniabad.info/public_html/application/controllers/PluginsController.php(95): Omeka_Plugin_Installer->install(Object(Plugin))
#10 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#11 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#12 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /srv/www/antoniabad.info/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /srv/www/antoniabad.info/public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#16 /srv/www/antoniabad.info/public_html/admin/index.php(28): Omeka_Application->run()
#17 {main}

**Comment by teo1978** [comment]
Apparently this is due to a bug in mysql that was fixed in 5.6.

At the very least you need to specify the minimum required version of mysql here:
https://omeka.org/classic/plugins/NeatlineTime/
(there are no system requirements whatsoever, actually, which is quite pathetic)

Also I'm pretty sure you can easily remove this requirement.

**Comment by jeremyboggs** [comment]
@teo1978 I've re-released the plugin, with the fix I included a few months ago. I just confirmed on my own machine, using MySQL 5.7, that installation works ok. This should resolve the installation issue you've encountered. I'm not sure when this will show up on the Omeka site (it should have showed up a month or so ago), but I'll reach out to them to confirm the latest version get published there. In the meantime, [you can find NeatlineTime 2.1.1 on the releases page](https://github.com/scholarslab/NeatlineTime/releases/tag/v2.1.1).

A lack of obvious system requirements is indeed lamentable, or pitiable, or any other definition of pathetic you intend, I suppose. It's a useful thing to include for sure. For better or worse, we've assumed the same system requirements as [Omeka Classic's system requirements](https://omeka.org/classic/docs/Installation/System_Requirements/). Not that it's a good excuse, but a lot Omeka plugins omit an explicit set of system requirements. Regardless, the fix I committed a little while back, and tagged and released earlier today, means that at the very least NeatlineTime should continue to comport Omeka Classic's system requirements.

**Comment by teo1978** [comment]
> This should resolve the installation issue you've encountered.

You mean the other one I commented on in another report, right?
This one I confirmed with the master branch from here.

> For better or worse, we've assumed the same system requirements as Omeka Classic's system requirements

Omeka Classic requires MySQL 5.0+, or so it states (and I didn't observe any issue on 5.5 before installing this plugin, but I admit I haven't tested it a lot), your plugin requires 5.6 (Or 5.7, now I'm not sure, I should check.) otherwise you encounter the installation error above.

**Comment by jeremyboggs** [comment]
> You mean the other one I commented on in another report, right? This one I confirmed with the master branch from here.

@teo1978 Yup, I think I'm crossing the streams. I'll see if I can get a container running with an earlier version of MySQL, see if I can replicate the problem you encounter, and see if a patch is easy enough. If not, we may just require MySQL 5.7 for the plugin going forward, and state that somewhere.

In addition to actually including a list of system requirements for the plugins, it'd be good for us to actually be more attentive to what those are. This is a oversight on my part, and I'll try to correct it here  and in our other plugins.

**Comment by jeremyboggs** [comment]
So, @teo1978, what version of MySQL are you using, when you encounter this exception?

**Comment by jeremyboggs** [comment]
The 2.1.1. release should address this issue, so I'm closing this ticket. If the problem exists, will reopen.
